const C="shaffer-v57";
const CORE=["/legacy/","/legacy/index.html","/legacy/tutu.html","/legacy/veil.html","/legacy/council.html","/legacy/family-line/","/legacy/apple-touch-icon.png","/legacy/icon-192.png","/legacy/icon-512.png","/legacy/manifest.webmanifest","/legacy/favicon.svg","/legacy/favicon.ico","/legacy/favicon-32.png","/legacy/billsr/photos/p1-kelly-field-1917-18.webp","/legacy/billsr/photos/p2-kelly-field-cockpit.webp","/legacy/billsr/photos/p3-curtiss-oriole-1920.webp","/legacy/billsr/photos/p4-wae-loening-duck.webp","/legacy/billsr/photos/p5-loening-catalina.webp","/legacy/billsr/photos/p6-wae-uniform-1932.webp","/legacy/billsr/clips/c1-1917-04-30-officers-reserve-camp.webp","/legacy/billsr/clips/c2-1920-08-02-honeymoon-in-plane.webp","/legacy/billsr/clips/c3-1922-02-19-plane-takes-cash-to-bank.webp","/legacy/billsr/clips/c4-1925-07-31-black-falcons-hop-off.webp","/legacy/billsr/clips/c5-1931-09-11-record-hop-from-la.webp","/legacy/billsr/clips/c6-1943-06-23-command-pilot-wings.webp"];
self.addEventListener("install",e=>{e.waitUntil(caches.open(C).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting()))});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==C).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",e=>{const r=e.request,u=new URL(r.url);
 if(r.method!=="GET"||u.origin!==location.origin||r.headers.has("range")||/\.mp4$/i.test(u.pathname))return;
 if(r.mode==="navigate"||u.pathname.endsWith("/")||u.pathname.endsWith(".html")){const key=/\/tutu\.html$/.test(u.pathname)?"/legacy/tutu.html":/\/veil\.html$/.test(u.pathname)?"/legacy/veil.html":/\/council\.html$/.test(u.pathname)?"/legacy/council.html":/\/family-line\//.test(u.pathname)?"/legacy/family-line/":"/legacy/";   // each page keeps its own offline copy
  e.respondWith(fetch(r,{cache:"no-store"}).then(res=>{if(res.ok){const cp=res.clone();caches.open(C).then(c=>c.put(key,cp))}return res}).catch(()=>caches.match(key)));return;}
 e.respondWith(caches.match(r).then(m=>m||fetch(r).then(res=>{if(res.ok){const cp=res.clone();caches.open(C).then(c=>c.put(r,cp))}return res})));});
